#cloud-config
manage_etc_hosts: true
chpasswd:
  expire: False
hostname: ${hostname}
fqdn: ${fqdn}
users:
  - default
  - name: setup
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ${pubkey}
packages: qemu-guest-agent

package_upgrade: true
bootcmd:
  - sysctl -w net.ipv4.ip_forward=1
  - apt update; apt-get install qemu-guest-agent nfs-common -y | tee /tmp/log
